# Creating Array via Array Module

In [1]:
import array

# Creation of array

In [15]:
arr1 = array.array('i' , [10,20,30,40,50])

In [3]:
arr1

array('i', [10, 20, 30, 40, 50])

### accessing the array

In [4]:
arr1[2]

30

### transversing

In [18]:
for element in arr1:
    print(element , end =" ")

10 20 40 50 

### inserstion

In [19]:
arr1.insert(3,35)

In [20]:
arr1

array('i', [10, 20, 40, 35, 50])

### deletion

In [16]:
arr1.remove(30)       # It will remove the first occurance in case of more values

In [21]:
arr1

array('i', [10, 20, 40, 35, 50])

### updating

In [23]:
arr1[2] = 30
arr1

array('i', [10, 20, 30, 35, 50])

### sorting

In [26]:
arr2 = array.array('i' , [60,70,80,40,10,20,90])

In [27]:
arr2

array('i', [60, 70, 80, 40, 10, 20, 90])

In [30]:
sorted_arr2 = array.array('i' ,sorted(arr2))

### merging

In [33]:
arr3 = arr1 + arr2

In [34]:
arr3

array('i', [10, 20, 30, 35, 50, 60, 70, 80, 40, 10, 20, 90])

In [35]:
ix = int(len(arr3)/2)

In [36]:
ix

6

In [38]:
arr3[:ix]

array('i', [10, 20, 30, 35, 50, 60])

In [40]:
arr3[ix:]

array('i', [70, 80, 40, 10, 20, 90])

# Creating Array via Numpy

In [41]:
import numpy as np

In [42]:
np1  = np.array([10,20,30,40,50])
np2 = np.array([40,50,10,20,30])

In [44]:
np1[1]

20

In [45]:
for i in np1:
    print(i , end= " ")

10 20 30 40 50 

In [46]:
np.insert(np1,3,35)

array([10, 20, 30, 35, 40, 50])

In [47]:
np.delete(np1, 3)

array([10, 20, 30, 50])

In [48]:
np1[2]= 35
np1

array([10, 20, 35, 40, 50])

In [51]:
np3 = np.sort(np2)

In [52]:
np3

array([10, 20, 30, 40, 50])

In [54]:
np3 = np1 + np2

In [62]:
np3 = np.concatenate((np1,np2))

In [63]:
split1 , split2 = np.array_split(np3 ,2)

In [64]:
split1

array([10, 20, 35, 40, 50])

In [65]:
split2

array([40, 50, 10, 20, 30])